<a href="https://colab.research.google.com/github/Fatai-soliu/python/blob/main/Advanced_Python_Bloomberg_Practice2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## Creating an Array
## Import libraries first

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
## Create an array

arr1 = np.arange(1,10,2)
print(arr1)

[1 3 5 7 9]


In [ ]:
# Reshaping an array after creating

arr2 = np.arange(20,100,10).reshape(8,1)
print(arr2)

[[20]
 [30]
 [40]
 [50]
 [60]
 [70]
 [80]
 [90]]


In [ ]:
## Creating an array using np.array

arr3 = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr3)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [ ]:
#If I want to slice this array, How can I do that?

print(arr3[0])
print(arr3[0][2])
print(arr3[1:,0])

[40 70]


In [ ]:
## Let us also calculate the mean

mean = arr3.mean()
print("The mean of this array is :", mean)

The mean of this array is : 50.0


In [ ]:
## Let us also calculate the standard deviation

std = arr3.std()
print("The standard deviation of this array is :", std)

The standard deviation of this array is : 25.81988897471611


In [ ]:
## Create another array but this time, we want to convert it to dataframe

student_data = np.array([[1,2,3,4,5],[14,12,10,9,15]])
print(student_data)

[[ 1  2  3  4  5]
 [14 12 10  9 15]]


In [ ]:
#Let me reshape it so that we have studentid on one column and student age on the other

student_data_reshape = student_data.reshape(2,5)
print(student_data_reshape)   ## This is wrong

In [ ]:
##Can I transpose in python, oh wow, I have been dulling myself lol

student_data_transpose = student_data.transpose()
print(student_data_transpose)

[[ 1 14]
 [ 2 12]
 [ 3 10]
 [ 4  9]
 [ 5 15]]


In [ ]:
# Let me convert student_data to a dataframe  (note: use [] when defining the columns header because it is mutable)

df = pd.DataFrame(student_data_transpose,columns=['student_id','Age'])
df

student_id  Age
0           1   14
1           2   12
2           3   10
3           4    9
4           5   15

In [ ]:
## Exercise - Creating a dataframe

data_dict = {
    'Name': ['Alice','Bob','Charlie','Diana'],
    'Age': [25,30,22,27],
    'Gender': ['F','M','M','F']
    }


df1 = pd.DataFrame(data_dict)

In [ ]:
df1

Name  Age Gender
0    Alice   25      F
1      Bob   30      M
2  Charlie   22      M
3    Diana   27      F

In [ ]:
## Exercise 2

countries = ['USA', 'Canada', 'Germany', 'France']
populations = [331, 38, 83, 67]


df2 = pd.DataFrame(populations, index = countries, columns=['Population'])
df2

Population
USA             331
Canada           38
Germany          83
France           67

In [ ]:
## Exercise 3

data = [
    {'student_id': 1, 'score': 95},
    {'student_id': 2, 'score': 88},
    {'student_id': 3, 'score': 92},
    {'student_id': 4, 'score': 79}
]

df3 = pd.DataFrame(data)
df3.set_index('student_id', inplace= True)
df3

score
student_id       
1              95
2              88
3              92
4              79

In [ ]:
#Exercise 3 (part 1)

products = [
    {'product_id': 101, 'product_name': 'Laptop', 'price': 1200},
    {'product_id': 102, 'product_name': 'Smarphone', 'price': 800},
    {'product_id': 103, 'product_name': 'Tablet', 'price': 500},
    {'product_id': 104 , 'product_name': 'Monitor'  ,'price': 500}
]

df4 = pd.DataFrame(products)
df4.set_index('product_id', inplace= True)
df4

product_name  price
product_id                    
101              Laptop   1200
102           Smarphone    800
103              Tablet    500
104             Monitor    500

In [ ]:
## Exercise 3 (part 2)

employees = [
    {'employee_id': 1, 'name': 'John', 'department': 'HR', 'salary': 50000},
    {'employee_id': 2, 'name': 'Emma', 'department': 'Finance', 'salary': 60000},
    {'employee_id': 3, 'name': 'Liam', 'department': 'IT', 'salary': 75000},
    {'employee_id': 4, 'name': 'Sophia', 'department': 'Marketing', 'salary': 45000}
]

df5 = pd.DataFrame(employees)
df5.set_index('employee_id', inplace = True)
df5

name department  salary
employee_id                           
1              John         HR   50000
2              Emma    Finance   60000
3              Liam         IT   75000
4            Sophia  Marketing   45000

In [ ]:
# Creating a DF from a Numpy Array  - This is wrojng, check correction below

arr7 = np.arange(1, 100).reshape(33,3)
arr7

df7 = pd.DataFrame(arr7, columns=['A','B','C'])
df7

In [ ]:
arr7 = np.random.randint(1, 101, size = (3, 3))

df7 = pd.DataFrame(arr7, columns=['A','B','C'])
df7

A   B   C
0  72  42  43
1  55  31  32
2  82  32  76

In [ ]:
# Exercise 5 Creating a DF with Date index  - The assessment is incomplete, see solution below

data = [[1,2,3],[10,15,20],[36,10,20],[24,10,14],[10,11,12]]

df6 = pd.DataFrame(data, columns = ['X','Y','Z'])
df6

X   Y   Z
0   1   2   3
1  10  15  20
2  36  10  20
3  24  10  14
4  10  11  12

In [ ]:
## Solution

data = [[1,2,3],[10,15,20],[36,10,20],[24,10,14],[10,11,12]]

df6 = pd.DataFrame(data, columns = ['X','Y','Z'])

## I have to create the date_index

df6.set_index(pd.date_range('2023-01-01', periods=5), inplace = True)

df6

X   Y   Z
2023-01-01   1   2   3
2023-01-02  10  15  20
2023-01-03  36  10  20
2023-01-04  24  10  14
2023-01-05  10  11  12

In [ ]:
## Extra exercises
"""
You have been tasked with generating a 5x4 NumPy array of random integers between 50 and 150, then convert it into a DataFrame. The columns of the DataFrame should be labeled as "W", "X", "Y", and "Z".
"""

arr9 = np.random.randint(50, 151, size = (5,4))

arr9

df9 = pd.DataFrame(arr9, columns = ['W','X','Y','Z'])
df9

W    X    Y    Z
0  109  101  148   85
1   56  131   86   53
2   97  120   97   54
3   93  117  116  101
4  116  122   54  116

In [ ]:
## Extra exercises
"""
Generate a 4x4 NumPy array of random integers between 1 and 50. Convert this array into a DataFrame with columns labeled "A", "B", "C", and "D".
Additionally, set the index of the DataFrame to the first four letters of the alphabet ("A", "B", "C", "D").
"""

arr10 = np.random.randint(1, 51, size = (4,4))

arr10

df10 = pd.DataFrame(arr10, columns = ['A','B','C','D'])

df10.index = ['A','B','C','D']
df10

A   B   C   D
A  50  19  26  31
B  35  10  25  26
C   2  38   6  32
D  13  27  21  36

In [ ]:
"""
Create a DataFrame with 6 rows and 2 columns of random floating-point values. Label the columns as "P" and "Q".
Set the index of the DataFrame to a date range starting from '2024-01-01' with a frequency of one day.
"""

data = np.random.rand(6, 2)   ## To generate the random floating plot, please use np.random.rand() , initially I used random.randit and specified size

df11 = pd.DataFrame(data, columns = ['P', 'Q'])

df11.index = pd.date_range("2024-01-01", periods = 6)
df11

P         Q
2024-01-01  0.854223  0.878968
2024-01-02  0.197251  0.646951
2024-01-03  0.196722  0.760541
2024-01-04  0.498364  0.624535
2024-01-05  0.650119  0.957772
2024-01-06  0.873316  0.471578

In [ ]:
"""
Create a DataFrame with 4 rows and 3 columns of random integer values between 10 and 50. Label the columns as "M", "N", and "O".
Set the index of the DataFrame to a date range starting from '2023-06-01', but use a frequency of two days between each row.
"""

data = np.random.randint(10, 51, size = (6, 2))

df12 = pd.DataFrame(data, columns = ['P', 'Q'])

df12.index = pd.date_range("2024-01-01", periods = 6, freq ='48h')
df12

P   Q
2024-01-01  18  25
2024-01-03  39  36
2024-01-05  46  50
2024-01-07  13  46
2024-01-09  10  11
2024-01-11  16  31

In [ ]:
"""
Create a DataFrame with 4 rows and 3 columns of random integer values between 10 and 50. Label the columns as "M", "N", and "O".
Set the index of the DataFrame to a date range starting from '2023-06-01', but use a frequency of two days between each row.
"""

data = np.random.randint(10, 51, size = (4, 3))

df13 = pd.DataFrame(data, columns = ['M', 'N', 'O'])

df13.index = pd.date_range("2024-06-01", periods = 4, freq ='72h')
df13

M   N   O
2024-06-01  45  20  27
2024-06-04  13  33  11
2024-06-07  20  40  19
2024-06-10  45  32  44

## Deeper Questions for Interviews

In [ ]:
"""
Exercise 1: DataFrame Filtering and Conditional Selection
"""

import pandas as pd
import numpy as np

data = {
    'employee_id':[1,2,3,4,5],
    'name': ['John', 'Jane', 'Emily', 'Micheal', 'Ella'],
    'age': [34, 29, 40, 50, 22],
    'department':['HR', 'Finance','IT', 'Marketing','Finance'],
    'salary': [50000, 60000, 75000, 65000, 45000]

}

df1 = pd.DataFrame(data)
df1.set_index('employee_id', inplace = True)
df1

name  age department  salary
employee_id                                 
1               John   34         HR   50000
2               Jane   29    Finance   60000
3              Emily   40         IT   75000
4            Micheal   50  Marketing   65000
5               Ella   22    Finance   45000

In [ ]:
filtered_df = df1[(df1['age'] < 30) & (df1['salary'] > 50000)]

sorted_df = filtered_df.sort_values(by = 'age', ascending = False)
sorted_df

name  age department  salary
employee_id                              
2            Jane   29    Finance   60000

In [ ]:
##Another example

data = {
    'student_id': [101, 102, 103, 104, 105, 106],
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank'],
    'math_score': [88, 92, 79, 85, 90, 73],
    'english_score': [91, 85, 89, 80, 78, 92],
    'science_score': [95, 89, 85, 77, 90, 88]
}

df2 = pd.DataFrame(data)
df2

filtered_df1 = df2[(df2['math_score'] > 80) & (df2['science_score'] > 80)]
filtered_df1

sorted_df1 = filtered_df1.sort_values(by = 'math_score', ascending=True)
sorted_df1

avg_science_score = sorted_df1['science_score'].mean()
avg_science_score

91.33333333333333

In [ ]:
##Another example

data = {
    'employee_id': [101, 102, 103, 104, 105, 106],
    'name': ['Alice', 'Bob', 'Charlie', 'David', None, 'Frank'],
    'age': [25, None, 35, 45, 29, None],
    'salary': [50000, 60000, None, 70000, 55000, None],
    'department': ['HR', 'Finance', 'IT', None, 'Finance', 'HR']
}

df3 = pd.DataFrame(data)

#fill missing and drop rows with Nan or None
df3['age'] = df3['age'].fillna(df3['age'].mean())
df3.dropna(subset=['salary', 'name'], inplace=True)

#Filter the dataframe

filtered_df3 = df3[(df3['age'] < 40) & (df3['department']=='Finance')]
filtered_df3

##Using Edge cases to handle cases where no rows meet condition

if not filtered_df3.empty:
  sorted_df3 = filtered_df3.sort_values(by='salary', ascending=True)
  print(sorted_df3)
else:
  print('No record was found')

   employee_id name   age   salary department
1          102  Bob  33.5  60000.0    Finance


In [ ]:
"""
Exercise 2: Grouping and Aggregating Data
"""
import pandas as pd

data = {
    'store_id': [1, 2, 1, 3, 2, 3, 1, 3, 2],
    'product': ['A', 'B', 'A', 'C', 'B', 'A', 'C', 'A', 'C'],
    'quantity_sold': [10, 20, 15, 5, 25, 30, None, 15, None],
    'unit_price': [100, 200, 100, 150, 200, 100, 150, 100, 150]
}

data

#Create dataframe
df7 = pd.DataFrame(data)

#Fill in missing values for quantity solde with the average quantity sold for that specific product

df7['quantity_sold'] = df7.groupby('product')['quantity_sold'].transform(lambda x: x.fillna(x.mean()))

#Add a new column total sales

df7['total_sales'] = df7['quantity_sold'] * df7['unit_price']

#Group by store_id and product and also sort

group_df7 = df7.groupby(['store_id','product'])[['quantity_sold','total_sales']].sum().sort_values(by='total_sales', ascending=False)
group_df7

quantity_sold  total_sales
store_id product                            
2        B                 45.0       9000.0
3        A                 45.0       4500.0
1        A                 25.0       2500.0
         C                  5.0        750.0
2        C                  5.0        750.0
3        C                  5.0        750.0

## Array Manipulation

In [2]:
##Example 1

"""
Given an array [1, 2, 3, 4, 5], rotate the array by 2 positions to the right:
"""
## The appraoch will, involve slicing the array

arr = [1, 2, 3, 4, 5]

def rotate_array(arr, k):
  # calculate the effective number of rotations
  n = len(arr)
  k = k % n # ensure k is within bounds of the array length

  #Rotate the array by slicing
  rotated_array = arr[-k:] + arr[:-k]  # The last element (arr[-k:]) + the first n - k element (arr[:-k])

  return rotated_array

In [4]:
# Apply the function

rotated_arr = rotate_array(arr, 2)
print(rotated_arr)

[4, 5, 1, 2, 3]


Slicing is the most effective way of handling array rotations in python

In [5]:
## In-place method - uses O(1) space complexity (constant space complexity)

def reverse(arr, start, end):
  while start < end:
    arr[start], arr[end] = arr[end], arr[start]
    start += 1
    end -= 1

def rotate_in_place(arr, k):
  n = len(arr)
  k = k % n  # In case k is greater than array length

  #Step 1: Reverse the entire array
  reverse(arr, 0, n - 1)

  #Step 2: Reverse the first k elements
  reverse(arr, 0, k - 1)

  #Step 3: Reverse the remaining n - k elements
  reverse(arr, k, n-1)

In [7]:
## Applying the function

arr = [1, 2, 3, 4, 5]
rotate_in_place(arr, 2)
print(arr)

[4, 5, 1, 2, 3]


In [19]:
## Exercise 1
def reverse(arr, start, end):
  while start < end:
    arr[start], arr[end] = arr[end], arr[start]
    start += 1
    end -= 1

def rotate_in_place(arr, k):
  n = len(arr)
  k = k % n

  #Reverse all arr
  reverse(arr, 0, n -1)

  #Reverse k element
  reverse(arr, 0, k - 1)

  #Reverse the rest of the element
  reverse(arr, k, n - 1)


In [20]:
arr2 = [10, 20, 30, 40, 50]
k = 2

rotate_in_place(arr2, k)
print(arr2)

[40, 50, 10, 20, 30]


In [25]:
## 3rd attempt

#Write the reverse function to reveerse the array - #The start and end are the beginning and ending of the arr

def reverse(arr, start, end):
  while start < end:
    arr[start], arr[end] = arr[end], arr[start]
    start += 1
    end -= 1

#After the reverse function, we write the rotate i place fucntion

def rotate_in_place(arr, k):
  n = len(arr)
  k = k % n  #To manage when k is greater than n

  #step 1, reverse the array
  reverse(arr, 0, n - 1)

  #step 2, reverse the k element of the array
  reverse(arr, 0, k - 1)

  #step 3, reverse the last k element of the array
  reverse(arr, k, n - 1)

In [26]:
## Now, let's rotate the array

arr3 = [1, 2, 3, 4, 5, 6]

rotate_in_place(arr3, 3)
print(arr3)

[4, 5, 6, 1, 2, 3]


## Sorting Algorithm

In [31]:
# Bubble Sort

def bubble_sort(arr):
  n = len(arr)
  for i in range(n):
    #Last i elements are already sorted
    for j in range(0, n - i - 1):
      #Swap if the element found is greater than the next element
      if arr[j] > arr[j + 1]:
        arr[j], arr[j + 1] =  arr[j + 1], arr[j]
  return arr

#Example usage:
arr = [64, 34, 25, 12, 22, 11, 90]
print(bubble_sort(arr))

[11, 12, 22, 25, 34, 64, 90]


In [32]:
##Let's rewrite bubble_sort

#First thing, define the function
def bubble_sort(arr):
  n = len(arr)

  for i in range(n):
    for j in range(0, n - i - 1):
      if arr[j] > arr[j + 1]:
        arr[j], arr[j + 1]= arr[j + 1], arr[j]
  return arr


#Usage
arr2 = [14, 10, 3, 20, 25, 3, 4, 60]
print(bubble_sort(arr2))

[3, 3, 4, 10, 14, 20, 25, 60]


Buddle sort is not efficient for large data but space complexity is constant

Time complexity = O(n^2)
Space complexity = O(1)

In [33]:
## Using Quick Sort, I will learn both Bubble and Quick Sort for the purpose of this interview

def quick_sort(arr):
  if len(arr) <= 1:
    return arr
  else:
    pivot = arr[len(arr) // 2]  #Choose the middle element as pivot
    left = [x for x in arr if x < pivot]  ## Elements less than pivot
    middle = [x for x in arr if x == pivot] ## Elements equal to pivot
    right = [x for x in arr if x > pivot] ## Elements greater than pivot
    return quick_sort(left) + middle + quick_sort(right)


# Example usage
arr = [10, 7, 8, 9, 1, 5]
print(quick_sort(arr))

[1, 5, 7, 8, 9, 10]


In [ ]:
"""
Exercise 3: Handling Missing Data
"""

In [ ]:
"""
Exercise 4: Applying Functions to a DataFrame
"""

In [ ]:
"""
Exercise 5: Merging DataFrames
"""

In [34]:
# Write the bubble sort algorith again

def bubble_sort2(arr):
  n = len(arr)

  for i in range(n):
    for j in range(0, n - i - 1):
      if arr[j] > arr[j + 1]:
        arr[j], arr[j + 1] = arr[j + 1], arr[j]
  return arr

#Example usage
arr = [10, 7, 8, 9, 1, 5]
print(bubble_sort2(arr))

[1, 5, 7, 8, 9, 10]


In [36]:
## Write the Quick sort algorithm as well

def quick_sort2(arr):
  if len(arr) <= 1:
    return arr
  else:
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quick_sort2(left) + middle + quick_sort2(right)

#Usage
arr3 = [14, 10, 3, 20, 25, 3, 4, 60]
print(quick_sort2(arr3))

[3, 3, 4, 10, 14, 20, 25, 60]


## Exploratory Data Analysis

The dataset i am using is World Happiness report. Contains variables about the global happiness between 2015 to 2023. There is 9 CSV for each year