<a href="https://colab.research.google.com/github/Fatai-soliu/python/blob/main/Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
list_data = [2, 4, 6, 8, 10, 12, 14]
list_data2 = [2, 3, 4, 5, 6, 7, 8]

In [ ]:
print(list_data)

[2, 4, 6, 8, 10, 12, 14]


In [ ]:
type(list_data)

list

In [ ]:
import numpy as np

In [ ]:
array_data = np.array(list_data)
array_data2  = np.array(list_data2)

In [ ]:
type(array_data)

numpy.ndarray

In [ ]:
print(array_data)

[ 2  4  6  8 10 12 14]


In [ ]:
# The difference between array and list is that array can perform numerial operation

division = array_data/array_data2

In [ ]:
print("The result of the division is valid:", division)

The result of the division is valid: [1.         1.33333333 1.5        1.6        1.66666667 1.71428571
 1.75      ]


In [ ]:
matrix = np.matrix(array_data)

In [ ]:
print(matrix)

[[ 2  4  6  8 10 12 14]]


In [ ]:
type(matrix)

numpy.matrix

In [ ]:
#Does matrix allow me to perform numerial operation?

Division = matrix/2

In [ ]:
print(Division)
print(type(Division))

[[1. 2. 3. 4. 5. 6. 7.]]
<class 'numpy.matrix'>


Week 2 - Data Preprocessing

In [ ]:
import pandas as pd

In [61]:
df = pd.read_csv("/content/drive/MyDrive/Datasets/Car Insurance.csv")

In [62]:
df.head()

Make   Age   Mileage Fuel Gearbox Colour Claimed
0  Toyota   2.0   27000.0    P       A    Red     Yes
1    Ford   4.0   30500.0    P       M  Black     Yes
2  Toyota  15.0  120000.0    D       A  White      No
3  Nissan  13.0   53000.0    D       M  White      No
4  Nissan   2.0       NaN    D       M  Black      No

In [70]:
#To select specific columns or row (which will then become a panda series)

subsetdf = df.iloc[:3,:3]

print(type(subsetdf))

<class 'pandas.core.frame.DataFrame'>


In [71]:
Makeser = df.iloc[:,0]

In [72]:
print(type(Makeser))

<class 'pandas.core.series.Series'>


In [73]:
df['Age']

0     2.0
1     4.0
2    15.0
3    13.0
4     2.0
5     8.0
6     NaN
7    20.0
8    13.0
9     7.0
Name: Age, dtype: float64